build:
  main: main.go
  binary: mvs
  ldflags: -s -w -X github.com/hofstadter-io/mvs/commands.Version={{.Version}} -X github.com/hofstadter-io/mvs/commands.Commit={{.ShortCommit}} -X github.com/hofstadter-io/mvs/commands.BuildDate={{.Date}}
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    arm: ARM
    arm64: ARM64
    darwin: MacOS
    linux: Linux
    windows: Windows
  files:
    - README.md
    - LICENSE

brew:
  name: mvs
  github:
    owner: hofstadter-io
    name: homebrew-tap
  folder: Formula
  commit_author:
    name: verdverm
    email: tony@hofstadter.io
  homepage: https://github.com/hofstadter-io/mvs
  description: 'MVS is a polyglot dependency management tool based on go mods'

release:
  draft: true
