project_name: "{% .CLI.cliName %}"

before:
  hooks:
    - go mod vendor

builds:
- binary: "{% .CLI.cliName %}"
  main: main.go

  ldflags:
    - -s -w
    - -X {% .CLI.Package %}/commands.Version=<no value>
    - -X {% .CLI.Package %}/commands.Commit=<no value>
    - -X {% .CLI.Package %}/commands.BuildDate=<no value>
    - -X {% .CLI.Package %}/commands.GoVersion=go1.14
    - -X {% .CLI.Package %}/commands.BuildOS=<no value>
    - -X {% .CLI.Package %}/commands.BuildArch=<no value>
    - -X {% .CLI.Package %}/commands.BuildArm=<no value>

  env:
  - CGO_ENABLED=0

  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - arm

  ignore:
  - goos: linux
    goarch: arm


snapshot:
  name_template: "<no value>-SNAPSHOT-<no value>"

archives:
- format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  # Needed hack for binary only uploads
  # For more information, check #602
  files:
   - "thisfiledoesnotexist*"


checksum:
  name_template: '<no value>_<no value>_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


release:
  disable: {% .CLI.Releases.Disable %}
  draft: {% .CLI.Releases.Draft %}
  github:
    owner: {% .CLI.Releases.GitHub.Owner %}
    name: {%  .CLI.Releases.GitHub.Repo %}

dockers:
- binaries:
    - {% .CLI.cliName %}
  skip_push: {% .CLI.Releases.Disabled %}
  dockerfile: ci/docker/Dockerfile.jessie
  image_templates:
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:<no value>"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:v<no value>.<no value>"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:v<no value>"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:latest"

  - "{% .CLI.Releases.Docker.Repo %}/<no value>:<no value>-debian"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:v<no value>.<no value>-debian"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:v<no value>-debian"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:latest-debian"


- binaries:
    - {% .CLI.cliName %}
  skip_push: {% .CLI.Releases.Disabled %}
  dockerfile: ci/docker/Dockerfile.scratch
  image_templates:
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:<no value>-scratch"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:v<no value>.<no value>-scratch"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:v<no value>-scratch"
  - "{% .CLI.Releases.Docker.Repo %}/<no value>:latest-scratch"
