project_name: "mvs"

before:
  hooks:
    - go mod vendor

builds:
- binary: "mvs"
  main: main.go

  ldflags:
    - -s -w
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.Version={{.Version}}
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.Commit={{.FullCommit}}
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.BuildDate={{.Date}}
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.GoVersion=go1.14
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.BuildOS={{.Os}}
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.BuildArch={{.Arch}}
    - -X github.com/hofstadter-io/mvs/cmd/mvs/cmd.BuildArm={{.Arm}}

  env:
  - CGO_ENABLED=0

  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - arm

  ignore:
  - goos: linux
    goarch: arm


snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"

archives:
- format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  # Needed hack for binary only uploads
  # For more information, check #602
  files:
   - "thisfiledoesnotexist*"


checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


release:
  disable: true
  draft: true
  github:
    owner: hofstadter-io
    name: mvs

dockers:
- binaries:
    - mvs
  skip_push: true
  dockerfile: ci/docker/Dockerfile.jessie
  image_templates:
  - "hofstadter/{{.ProjectName}}:{{.Tag}}"
  - "hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
  - "hofstadter/{{.ProjectName}}:v{{ .Major }}"
  - "hofstadter/{{.ProjectName}}:latest"

  - "hofstadter/{{.ProjectName}}:{{.Tag}}-debian"
  - "hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}-debian"
  - "hofstadter/{{.ProjectName}}:v{{ .Major }}-debian"
  - "hofstadter/{{.ProjectName}}:latest-debian"


- binaries:
    - mvs
  skip_push: true
  dockerfile: ci/docker/Dockerfile.scratch
  image_templates:
  - "hofstadter/{{.ProjectName}}:{{.Tag}}-scratch"
  - "hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}-scratch"
  - "hofstadter/{{.ProjectName}}:v{{ .Major }}-scratch"
  - "hofstadter/{{.ProjectName}}:latest-scratch"
